<a href="https://colab.research.google.com/github/RiddhiKapoor5501/DeepLearning-using-TensorFlow/blob/main/TensorFlow_Tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import tensorflow as tf

In [3]:
tensor_zero_d = tf.constant(4) #zero d matrix or tensor
print(tensor_zero_d)

tf.Tensor(4, shape=(), dtype=int32)


In [5]:
tensor_one_d = tf.constant([2.0,0,-3])
print(tensor_one_d)

tf.Tensor([ 2.  0. -3.], shape=(3,), dtype=float32)


In [8]:
tensor_two_d = tf.constant([[1,2,3], [4,5,6],[7,8,9]])
print(tensor_two_d)

tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)


In [5]:
tensor_three_d = tf.constant([[[1,2,0],[3,5,-1]],[[10,2,0],[1,0,2]]])
print(tensor_three_d)

tf.Tensor(
[[[ 1  2  0]
  [ 3  5 -1]]

 [[10  2  0]
  [ 1  0  2]]], shape=(2, 2, 3), dtype=int32)


In [10]:
tensor_string = tf.constant(["Hello World","hi"])
print(tensor_string)

tf.Tensor([b'Hello World' b'hi'], shape=(2,), dtype=string)


In [11]:
import numpy as np

In [12]:
np_array = np.array([1,2,4])
print(np_array)

[1 2 4]


In [16]:
converted_tensor = tf.convert_to_tensor(np_array)
print(converted_tensor)#read documentation of tensorflow

tf.Tensor([1 2 4], shape=(3,), dtype=int64)


In [18]:
eye_tensor = tf.eye(  #equialent to identity matrix
    num_rows = 3,
    num_columns = None,
    batch_shape = [3,],
    dtype = tf.dtypes.float32,
    name = None
)
print(eye_tensor)

tf.Tensor(
[[[1. 0. 0.]
  [0. 1. 0.]
  [0. 0. 1.]]

 [[1. 0. 0.]
  [0. 1. 0.]
  [0. 0. 1.]]

 [[1. 0. 0.]
  [0. 1. 0.]
  [0. 0. 1.]]], shape=(3, 3, 3), dtype=float32)


In [19]:
fill_tensor = tf.fill(
    [1,3,4],5, name = None
)
print(fill_tensor)

tf.Tensor(
[[[5 5 5 5]
  [5 5 5 5]
  [5 5 5 5]]], shape=(1, 3, 4), dtype=int32)


In [21]:
random_tensor = tf.random.normal(
    [3,2],
    mean = 100.0,
    stddev = 1.0,
    dtype = tf.dtypes.float32,
    seed = None,
    name = None
)
print(random_tensor)

tf.Tensor(
[[ 0.98530716 -0.43915257]
 [ 0.04967504  0.6512693 ]
 [ 0.0164528   0.44211376]], shape=(3, 2), dtype=float32)


In [23]:
tensor_indexed = tf.constant([3,6,2,4,6,66,7])
print(tensor_indexed)
print(tensor_indexed[0:4])

tf.Tensor([ 3  6  2  4  6 66  7], shape=(7,), dtype=int32)
tf.Tensor([3 6 2 4], shape=(4,), dtype=int32)
